### ISSUE TITLE
font style won't work

### ISSUE THREAD

**Issue by raccoonlegs** [ribozone/layouts#1]
i downloaded both of the fonts and have them on my dashboard on neocities, and the amoeba.css won't use the fonts!

**Comment by ribozone** [comment]
do you have the files set up like they are here? the `.html` and `.css` file should be in the root directory (what you see on https://neocities.org/dashboard) and the font files should be in a folder named `fonts`.

**Comment by raccoonlegs** [comment]
i just put the fonts into a folder named fonts and everything else i already had but its still not working

**Comment by ribozone** [comment]
try doing a hard refresh when looking at your site. keyboard shortcut: Ctrl+Shift+R

**Comment by raccoonlegs** [comment]
ive been refreshing and tried reuploading the fonts and css file

**Comment by ribozone** [comment]
what is the link to your site?

**Comment by raccoonlegs** [comment]
https://raccoonlegs.neocities.org/music heres the one im testing it on

**Comment by ribozone** [comment]
<img alt="error" src="https://github.com/user-attachments/assets/d30e287e-4723-464e-9a22-2c3fa588bc26">

these are the error messages i'm getting on your page.
the top one means there's no file named `Director-Regular.woff` in your `fonts` folder, so it's either named incorrectly or it's in the wrong folder. the names have to match what i'm telling you exactly.
the second error means there's a file in the right place, but there's something wrong with it. i downloaded the font file from your website, and it says the file is 0 bytes, so there's no data there. when you downloaded the files originally, were they in a `.zip` folder? if so, you have to unzip that folder before you can upload the files to neocities.

**Comment by raccoonlegs** [comment]
it worked! thanks so much!!
